---
- name: homebrew update
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true
  tags:
    - homebrew
    - mas
    - mac-app-store

- name: homebrew package upgrade
  homebrew_cask:
    upgrade_all: true
  tags:
    - homebrew_cask
    - mas
    - mac-app-store

- name: homebrew taps are enabled
  homebrew_tap:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ homebrew_taps }}"
  tags: homebrew, homebrew_cask

- name: homebrew packages are installed
  community.general.homebrew:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ homebrew_installed_packages }}"
  tags: homebrew

- name: homebrew cask packages are installed
  community.general.homebrew_cask:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ homebrew_cask_installed_packages }}"
  tags: homebrew_cask

- name: python symbolic link are created
  file:
    src: /opt/homebrew/bin/python3
    dest: /opt/homebrew/bin/python
    state: link

- name: copy delete-emacs-pkg.sh
  copy:
    src: delete-emacs-pkg.sh
    dest: /usr/local/bin/delete-emacs-pkg.sh
    owner: root
    group: wheel
    mode: 0755
  become: yes

- name: copy update-brew.sh
  copy:
    src: update-brew.sh
    dest: /usr/local/bin/update-brew.sh
    owner: root
    group: wheel
    mode: 0755
  become: yes

- name: Importing mas tasks
  import_tasks: mas.yml
  tags:
    - mas
    - mac-app-store

